server.port=8080

# MySQL??
spring.datasource.url=jdbc:mysql://localhost:3306/mer?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=112605
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ????
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=2625791372@qq.com
spring.mail.password=izmxywpjejnfdjai
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# ??????
#file.upload-dir=./uploads/

# ===== ???? =====
file.storage.type=cos

# ===== ??? COS ?? =====
cos.secretId=AKIDvlU4Tm8PpBOPFsLhw0sXzGLm13uZ1GPL
cos.secretKey=lJfqtmSxHPJ5h6ScbP2SfhV6V5TdaKtF
cos.bucketName=pandora-1386250493
cos.region=ap-beijing
cos.baseUrl=https://pandora-1386250493.cos.ap-beijing.myqcloud.com

# ===== ???? =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== ???? =====
logging.level.com.example.demo=DEBUG
logging.level.com.qcloud.cos=DEBUG

feishu.bot.webhook=https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-id